{% set version = "8.0" %}

package:
  name: openmesh
  version: {{ version }}

source:
  fn: OpenMesh-{{ version }}.tar.gz
  url: https://graphics.rwth-aachen.de:9000/OpenMesh/OpenMesh/repository/archive.tar.gz?ref=OpenMesh-{{ version }}
  sha256: 245a0dc7db5dddc0cb31b8dc3e39f17ee3a688989e99a39e0438b97ec0895257

build:
  number: 0

  # https://graphics.rwth-aachen.de:9000/OpenMesh/OpenMesh/issues/29
  skip: true  # [win and py>=35]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f ${PREFIX}/lib/libOpenMeshCore.7.1.dylib  # [osx]
    - test -f ${PREFIX}/lib/libOpenMeshTools.7.1.dylib  # [osx]
    - test -f ${PREFIX}/lib/libOpenMeshCore.so.7.1  # [linux]
    - test -f ${PREFIX}/lib/libOpenMeshTools.so.7.1  # [linux]
    - if not exist %PREFIX%\\Library\\bin\\OpenMeshCore.7.1.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\OpenMeshTools.7.1.dll exit 1  # [win]

about:
  home: http://www.openmesh.org/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: OpenMesh is a generic and efficient data structure for representing and manipulating polygonal meshes.

extra:
  recipe-maintainers:
    - ivoflipse
    - EelcoHoogendoorn
