{% set version = "8.0" %}

package:
  name: openmesh
  version: {{ version }}

source:
  fn: OpenMesh-{{ version }}.tar.gz
  url: http://www.openmesh.org/media/Releases/{{ version }}/OpenMesh-{{ version }}.tar.gz
  sha256: 8974d44026cacaa37b171945b5c96a284bfd32c9df9d671d62931050d057ec82

build:
  number: 0

  # https://graphics.rwth-aachen.de:9000/OpenMesh/OpenMesh/issues/29
  skip: true  # [win and py>=35]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f ${PREFIX}/lib/libOpenMeshCore.{{ version }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/libOpenMeshTools.{{ version }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/libOpenMeshCore.so.{{ version }}  # [linux]
    - test -f ${PREFIX}/lib/libOpenMeshTools.so.{{ version }}  # [linux]
    - if not exist %PREFIX%\\Library\\bin\\OpenMeshCore.{{ version }}.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\OpenMeshTools.{{ version }}.dll exit 1  # [win]

about:
  home: http://www.openmesh.org/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: OpenMesh is a generic and efficient data structure for representing and manipulating polygonal meshes.

extra:
  recipe-maintainers:
    - ivoflipse
    - EelcoHoogendoorn
