{% set version = "7.0" %}

package:
  name: openmesh
  version: {{ version }}

source:
  fn: OpenMesh-{{ version }}.tar.gz
  url: https://graphics.rwth-aachen.de:9000/OpenMesh/OpenMesh/repository/archive.tar.gz?ref=OpenMesh-{{ version }}
  sha256: 44a10bf27793c544ffa043b9c919e7396ed59e798e0891b9180086027da48e77
  patches:
    # https://graphics.rwth-aachen.de:9000/OpenMesh/OpenMesh/merge_requests/81
    # https://graphics.rwth-aachen.de:9000/OpenMesh/OpenMesh/commit/c8ebba7492358059aad10d0eb3ec64feec470055
    - updated-output-directories.patch 

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc14  # [win and py>=35]

  # https://graphics.rwth-aachen.de:9000/OpenMesh/OpenMesh/issues/29
  skip: true  # [win and py>=35]

requirements:
  build:
    - toolchain
    - python
    - cmake
    - boost 1.66.*
  run:
    - python
    - boost 1.66.*

test:
  imports:
    - openmesh

about:
  home: http://www.openmesh.org/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: OpenMesh is a generic and efficient data structure for representing and manipulating polygonal meshes.

extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - EelcoHoogendoorn
    - xantares
