appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: eobEBRu7mEZpln+fur/8qw2aZzUZs87fPK64MbZXt19UJTqCwbfajEt3uLbztmAp8xo048XS1tTYuTF18z8WaAu0XW4LLx4DfgsZHw6UxkephyBgyrGglsmaIOVv4jHhMFlbuRsGsODPARa0z9ppCbo8ZEnYMxeDDQ06feqxA/nbrljgBG3i9dNmypqqJCbO9g6RKg6Ini7JKWC4AOcy5UqjhgUQRizPVBAuYhP6DoOLbIBlDeciHkWfSV0tjeSpdZdQcXq/p7hhPX6F5re9hyZQDWMbsVBVTXQk4CYyVw0tEXFNDw7c53/loyHPnIy3/MUzoUOIko3mWKqbNRw+P+0g8eK9BrGL/zHouilXP0g8WaG/iDL253ksu8Lv7K78S2VwBTt0vEUb+zS1miEIvOvhtycupfAtLjPfCh4M3VT8t27YAADTnUi4hvgmPnPN0lb7tHBHjbEsskkv1gJIY+6lW6mvfgIc9fhCMKb8ZXJL7nK63VnDcjZyJavZsgadcCrOhIGcoyw1yU1d66GVDbOYvQ7Mgh5U+JBc75SdRvc47Rpl3Sj0EciPe7Hx7m0VGqGMgtAOzKtJgEqZ9nhtHy4j34qT851D3V01uKkp7ZDBOrgoNt5OKoId/9NL+arOw5k+KZRRXOOtI0BVlK4VKDvse37QZzJN+l6qa/8l+Ow=}
provider:
  win: azure
conda_forge_output_validation: true
